[package]
name = "wt_datamine_extractor"
version = "0.2.0"
edition = "2018"

[lib]
name = "wt_datamine_extractor_lib"
path = "src/lib/lib.rs"

[[bin]]
name = "wt_datamine_extractor_bin"
path = "src/bin/main.rs"

[dependencies]
serde = { version = "1.*", features = ["derive"] }
serde_json = "1.*"