[package]
name = "wt_datamine_extractor"
version = "0.2.0"
edition = "2018"

[lib]
name = "wt_datamine_extractor_lib"
path = "src/lib/lib.rs"

[[bin]]
name = "wt_datamine_extractor_bin"
path = "src/bin/main.rs"

[profile.release]
# This makes the compiled code faster and smaller, but it makes compiling slower,
# so it's only enabled in release mode.
opt-level = "s"
debug = true
split-debuginfo = '...'  # Platform-specific.
debug-assertions = true
overflow-checks = true
lto = true
incremental = true
codegen-units = 8
rpath = false

[dependencies]
serde = { version = "1.*", features = ["derive"] }
serde_json = "1.*"
regex = "^1.5.4"