name: Datamine update

on:
  schedule:
    - cron:  '0 * * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  check-update:

    runs-on: ubuntu-latest

    steps:
      # Checkout self
      - name: Download self version
        id: set-self
        run: echo "::set-output name=SELF_FILE::${{ curl https://raw.githubusercontent.com/Warthunder-Open-Source-Foundation/wt_datamine_extractor/nightly/meta_index/version.txt }}"

      # Checkout datamine repo
      - name: Download other version
        id: set-other
        run: echo "::set-output name=OTHER_FILE:: ${{  curl -L https://api.github.com/repos/gszabi99/War-Thunder-Datamine/commits/master | jq '.commit.message'}}"

  run-update:
    runs-on: ubuntu-latest

    needs: check-update
    if: "${{ steps.set-self.outputs.SELF_FILE }} != ${{ steps.set-other.outputs.OTHER_FILE }}"

    steps:

      - name: yeet
        run: echo yeet